{% set name = "pygeohash" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 750e51643e743eabd065a84fc8c1912c5843b648143137919e4a9776366d921e

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygeohash

about:
  home: https://github.com/wdm0006/pygeohash
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE.txt
  summary: 'A module for decoding and encoding geohashes to and from latitude and longitude coordinates'

  description: |
    Pygeohash is a Python module that provides functions for
    decoding and encoding geohashes to and from latitude and
    longitude coordinates, and doing basic calculations and
    approximations with them.


extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - adbeda
    - agcopenhaver
    - oblute
